name: Infraestructure Actions

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main
    paths:
      - terraform/**

permissions:
  contents: read
  pull-requests: write

jobs:
  EXEC_INFRACOST:
    name: Infracost Checks
    uses: davidlimacardoso/github-actions/.github/workflows/infracost.yml@main
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
  
  EXEC_TERRAFORM:
    name: Terraform Plan & Apply
    uses: davidlimacardoso/github-actions/.github/workflows/terraform-plan-apply.yml@main