#https://github.com/kontrolplane/pull-request-title-validator
name: Validate PR Title
on: pull_request

permissions:
  pull-requests: read

jobs:
  validator:
    name: validate-pull-request-title
    runs-on: ubuntu-latest
    steps:
      - name: validate pull request title
        uses: kontrolplane/pull-request-title-validator@v1.3.2
        with:
          types: "fix,feat,chore,docs"
