name: Validate PR Title
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(feat|fix|docs|add)/.++" # Regex the title should match.
          helpMessage: "Example: 'feat/some_thing_example_of_title'"
