name: Continuos Tests Integration PR 

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: run install
        run: npm install

      - name: run build
        run: npm run build

      - name: run test
        run: npm test          